export { default as Heading } from './Heading'
export { default as Image } from './Image'
export { default as Loader } from './Loader'
export { default as NotFound } from './NotFound'
export { default as Pagination } from './Pagination'